name: Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - "module06/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]
    environment: ${{ matrix.environment }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifact
          path: ./artifact

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Azure login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM_* for Terraform
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Extract artifact
        run: tar -xzf artifact/terraform-*.tar.gz -C ./artifact

      - name: Run deployment script
        working-directory: module06
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh ${{ matrix.environment }} ../artifact/extracted